name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 12 * * *' # Runs at 12:00 UTC every day.
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest youtube videos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCp28AG2NaDuzyVaAT--2NGQ"
          max_post_count: 7
          commit_message: Updated with the latest YouTube videos
          comment_tag_name: "YOUTUBE"
          custom_tags: "videoId/yt:videoId/"
          date_format: "mmm d, yyyy"
          template: '<table><tr><td><a href="$url"><img width="80px" src="https://i.ytimg.com/vi/$videoId/mqdefault.jpg"></a></td>$newline<td><a href="$url">$title</a><br/>$date</td></tr></table>$newline'
